@startuml
'https://plantuml.com/sequence-diagram

actor Client


Client -> Website_Update_Dog_Page : Submit 'Update Dog' form
Website_Update_Dog_Page -> UpdateDogActivity : Update Dog request

database Dogs
UpdateDogActivity -> Dogs : save update dog to database

@enduml